init python:
    def get_all_game_variables():
         #Get semua variabel game yang terdeteksi
        vars_dict = {}
        all_vars = [
            "Hour",
            "about",
            "addedchoicerepeat",
            "afm_time",
            "aphropack",
            "b_fightback",
            "badgrds",
            "bar_size",
            "bbm",
            "bcaught_s",
            "bchar",
            "bdtchr",
            "beach",
            "beachalone",
            "beachdone",
            "beachelainedone",
            "beachrowenadone",
            "bexercise",
            "bgmt",
            "bikini1",
            "bikini2",
            "bikini3",
            "binstaexp",
            "bname",
            "bnamefixcheryl",
            "bnomn",
            "bought_followers",
            "bpee_dom",
            "bphotonaked",
            "browenabm",
            "bs_sex",
            "bstudied",
            "bstudy",
            "btoiuse",
            "btoldcheryl",
            "button_text_size",
            "button_text_xalign",
            "buy_s_phonecounter",
            "bworked",
            "bworkstarted",
            "callmel",
            "camerafixing",
            "camerarecording",
            "camerarecording1",
            "camerarecording2",
            "camerasacquired",
            "camexpose",
            "cellshop",
            "chbopen",
            "cherylevent",
            "cherylfoundout",
            "cherylintro",
            "cherylintrodone",
            "cherylvisitstrip",
            "choice_button_text_hover_color",
            "choice_button_text_idle_color",
            "choice_button_text_insensitive_color",
            "choice_button_text_xalign",
            "choice_button_width",
            "choice_spacing",
            "color",
            "completed",
            "confirm_button_text_xalign",
            "contactrowena",
            "coversname",
            "cselaine0",
            "ctempted",
            "current_tab",
            "cvisit",
            "dancerepeat",
            "day",
            "dayname",
            "device",
            "dialogue_text_xalign",
            "dialogue_width",
            "dialogue_xpos",
            "dialogue_ypos",
            "dollnightw",
            "dphonestolen",
            "drinkforbname",
            "e_showsupagain",
            "ebizaldoneonce",
            "ebizcheck",
            "edpills",
            "elaine_convince",
            "elaineagain",
            "elaineboobs",
            "elainefuck",
            "elaineshowsup",
            "elfllowup",
            "erel",
            "etvelaine",
            "file_slot_cols",
            "file_slot_rows",
            "findwindow",
            "gallery_unlocked",
            "game_menu_background",
            "giftcardrepeat",
            "gnight",
            "go_counter",
            "hallcamcheckm",
            "hallcamera",
            "hallcamerachecked",
            "hallcameracheckedm",
            "hidetoiletrowena",
            "history_height",
            "history_length",
            "history_name_width",
            "history_name_xalign",
            "history_name_xpos",
            "history_name_ypos",
            "history_text_width",
            "history_text_xalign",
            "history_text_xpos",
            "history_text_ypos",
            "hotphotos_done",
            "instadone",
            "instatalkm",
            "instauploads",
            "instresearchdone",
            "interface_text_font",
            "interface_text_size",
            "jenopen",
            "jenteaselingerie",
            "kissrepeat",
            "label_text_size",
            "language",
            "laptoprequested",
            "lesbianchannel",
            "locked_button",
            "m_bbruises",
            "main_menu_background",
            "main_menu_text_xalign",
            "mbag",
            "mbikini",
            "mbikinirequest",
            "mboobskiss",
            "mboobstalk",
            "mbphoto",
            "mbtv",
            "mbunknown",
            "mburnt",
            "mbvisit",
            "mcallcheryl",
            "mchar",
            "mcorr",
            "mdom",
            "melchar",
            "meldan",
            "melindafiles",
            "melmeeting",
            "melmilin",
            "melrel",
            "melsw",
            "melvisit",
            "melwork",
            "menjoyedtheview",
            "mfuckedsober",
            "mgready",
            "mhate",
            "microskirt1",
            "mmirror",
            "mmorningrepeat",
            "mnailpolish",
            "mname",
            "mnameboobs",
            "mnightie",
            "mnurse_im",
            "mnurseoutfit",
            "mnvylingerie",
            "mny",
            "mobilephoneacquired",
            "mphotoediting",
            "mphotos",
            "mpracticegift",
            "mrel",
            "mrob",
            "mrpmt",
            "msconvince",
            "msex",
            "msexreturn",
            "msexwork",
            "msfkd",
            "msho",
            "mstripseen",
            "msuspbs",
            "mtoiletsuspicious",
            "mtrelax",
            "mvisitnudebeach",
            "mwork",
            "mwvisit",
            "nadiaasksforstrongdrinks",
            "naivetalk",
            "name",
            "name_text_font",
            "name_text_size",
            "name_xalign",
            "name_xpos",
            "name_ypos",
            "navigation_spacing",
            "navigation_xpos",
            "neibrep",
            "notify_text_size",
            "notify_ypos",
            "nude_binsta_random1_posted",
            "nudebeachtalk",
            "nvl_button_width",
            "nvl_button_xalign",
            "nvl_button_xpos",
            "nvl_height",
            "nvl_list_length",
            "nvl_name_width",
            "nvl_name_xalign",
            "nvl_name_xpos",
            "nvl_name_ypos",
            "nvl_spacing",
            "nvl_text_width",
            "nvl_text_xalign",
            "nvl_text_xpos",
            "nvl_text_ypos",
            "nvl_thought_width",
            "nvl_thought_xalign",
            "nvl_thought_xpos",
            "nvl_thought_ypos",
            "page_name_value",
            "page_spacing",
            "pagecheck",
            "pagecheckdone",
            "pornchanel",
            "pref_button_spacing",
            "pref_spacing",
            "pullsb_repeat",
            "quick_button_text_size",
            "quick_menu",
            "rbkisscounter",
            "rdf",
            "report_content",
            "rkiss",
            "robel",
            "robmvisit",
            "rorepeat",
            "rosdad",
            "rowena_mom",
            "rowena_mom_called",
            "rowena_mom_number",
            "rowenabffuck",
            "rowenacall",
            "rowenadp",
            "rowenamove",
            "rowenaslap",
            "rvisit",
            "rwena",
            "s_bbruises",
            "saction",
            "sactiondone_mast",
            "sactiondone_nomast",
            "sanal",
            "save_directory",
            "sbesecret",
            "sbexerrepeat",
            "sblowjobdone",
            "sbm",
            "sbmrepeat",
            "sburnt",
            "schar",
            "scorr",
            "scroll",
            "scrollbar_size",
            "sdildo",
            "sdom",
            "sfedup",
            "sflirtwithotherguys",
            "sgmtb",
            "sgoestost",
            "sgrm",
            "sgtruth",
            "shj",
            "showcoverpage",
            "size",
            "skip_ypos",
            "skiss",
            "skiss_asked",
            "slider_size",
            "slot_button_height",
            "slot_button_text_size",
            "slot_button_text_xalign",
            "slot_button_width",
            "slot_spacing",
            "sm_rel",
            "smaid",
            "smalonenight",
            "smobilegiven",
            "smoneym",
            "snaked_lunch",
            "sname",
            "snamedrink",
            "snamedrinkminus",
            "snameinstaconvinced",
            "snameworkmelinda",
            "snupset",
            "sphotos_progress",
            "spiercings",
            "spreg",
            "spregnantno",
            "springstring",
            "srbm",
            "srel",
            "sroom13underss",
            "sroomride",
            "sscall",
            "sstrip",
            "stalkb_rowena",
            "stalkdone",
            "stalkrp",
            "startnework",
            "staway",
            "stewartcalled",
            "stewcalled",
            "stknw",
            "strongdrinksforgirlnight",
            "sundaysex",
            "swindowchecked",
            "text_cps",
            "text_font",
            "text_size",
            "text_width",
            "text_xpos",
            "textbox_height",
            "textbox_yalign",
            "thong",
            "thumbnail_height",
            "thumbnail_width",
            "ticketrequested",
            "title_text_size",
            "toidoorscrew",
            "tvwatched",
            "unscrollable",
            "valshoes",
            "version",
            "willmeeting",
            "window",
            "window_icon",
            "windowfound",
            "work_intro",
            "workrequest",
            "worktalk",
            "wrkquestions",
            "wrokmelindrp",
            "xalign",
            "yalign",
            "yinitial",
        ]
        
        for var_name in all_vars:
            try:
                if hasattr(store, var_name):
                    vars_dict[var_name] = getattr(store, var_name)
                else:
                    vars_dict[var_name] = "NOT_FOUND"
            except Exception as e:
                vars_dict[var_name] = f"ERROR: {str(e)}"
        
        return vars_dict
    
    def create_comprehensive_report():
         #Buat laporan lengkap dengan semua variabel
        variables = get_all_game_variables()
        
        # Group by category
        report = "=== COMPREHENSIVE GAME REPORT ===\n\n"
        
        # RELATIONSHIPS
        report += "--- RELATIONSHIPS ---\n"
        for var in sorted(['srel', 'mrel', 'erel', 'melrel', 'mtrelax', 'sm_rel']):
            if var in variables:
                report += f"{var}: {variables[var]}\n"
        report += "\n"
        
        # PROGRESS
        report += "--- PROGRESS ---\n"
        for var in sorted(['elaine_convince', 'msconvince', 'snameinstaconvinced', 'sphotos_progress']):
            if var in variables:
                report += f"{var}: {variables[var]}\n"
        report += "\n"
        
        # ITEMS
        report += "--- ITEMS ---\n"
        for var in sorted(['mobilephoneacquired', 'camerasacquired', 'bought_followers', 'mbunknown']):
            if var in variables:
                report += f"{var}: {variables[var]}\n"
        report += "\n"
        
        # FLAGS
        report += "--- FLAGS ---\n"
        for var in sorted(['gallery_unlocked', 'ebizaldoneonce', 'instadone', 'completed', 'hotphotos_done', 'sactiondone_nomast', 'sactiondone_mast', 'sblowjobdone', 'cherylintrodone', 'stalkdone', 'pagecheckdone', 'beachdone', 'beachelainedone', 'beachrowenadone', 'instresearchdone']):
            if var in variables:
                report += f"{var}: {variables[var]}\n"
        report += "\n"
        
        # TIME
        report += "--- TIME ---\n"
        for var in sorted(['Hour', 'day', 'afm_time', 'dayname', 'sundaysex']):
            if var in variables:
                report += f"{var}: {variables[var]}\n"
        report += "\n"
        
        # OTHER
        report += "--- OTHER ---\n"
        for var in sorted(['mdom', 'sdom', 'scorr', 'mcorr', 'mny', 'current_tab', 'color', 'size', 'nadiaasksforstrongdrinks', 'bs_sex', 'melsw', 'valshoes', 'dollnightw', 'bbm', 'callmel', 'melmilin', 'melindafiles', 'willmeeting', 'cherylfoundout', 'dphonestolen', 'cherylevent', 'ticketrequested', 'mbag', 'mbikini', 'mnightie', 'msho', 'bnamefixcheryl', 'mnailpolish', 'cselaine0', 'e_showsupagain', 'camerarecording', 'camerarecording1', 'camerarecording2', 'elaineshowsup', 'elaineagain', 'mburnt', 'drinkforbname', 'etvelaine', 'bcaught_s', 'locked_button', 'xalign', 'yalign', 'strongdrinksforgirlnight', 'lesbianchannel', 'text_font', 'name_text_font', 'interface_text_font', 'text_size', 'name_text_size', 'interface_text_size', 'label_text_size', 'notify_text_size', 'title_text_size', 'main_menu_background', 'game_menu_background', 'textbox_height', 'textbox_yalign', 'name_xpos', 'name_ypos', 'name_xalign', 'dialogue_xpos', 'dialogue_ypos', 'dialogue_width', 'dialogue_text_xalign', 'button_text_xalign', 'confirm_button_text_xalign', 'quick_button_text_size', 'choice_button_width', 'choice_button_text_xalign', 'choice_button_text_idle_color', 'choice_button_text_hover_color', 'choice_button_text_insensitive_color', 'slot_button_width', 'slot_button_height', 'slot_button_text_size', 'slot_button_text_xalign', 'thumbnail_width', 'thumbnail_height', 'file_slot_cols', 'file_slot_rows', 'navigation_xpos', 'skip_ypos', 'notify_ypos', 'choice_spacing', 'navigation_spacing', 'pref_spacing', 'pref_button_spacing', 'page_spacing', 'slot_spacing', 'main_menu_text_xalign', 'bar_size', 'scrollbar_size', 'slider_size', 'unscrollable', 'history_length', 'history_height', 'history_name_xpos', 'history_name_ypos', 'history_name_width', 'history_name_xalign', 'history_text_xpos', 'history_text_ypos', 'history_text_width', 'history_text_xalign', 'nvl_list_length', 'nvl_height', 'nvl_spacing', 'nvl_name_xpos', 'nvl_name_ypos', 'nvl_name_width', 'nvl_name_xalign', 'nvl_text_xpos', 'nvl_text_ypos', 'nvl_text_width', 'nvl_text_xalign', 'nvl_thought_xpos', 'nvl_thought_ypos', 'nvl_thought_width', 'nvl_thought_xalign', 'nvl_button_xpos', 'nvl_button_xalign', 'language', 'button_text_size', 'text_xpos', 'text_width', 'nvl_button_width', 'worktalk', 'bgmt', 'cvisit', 'mrob', 'rwena', 'rosdad', 'contactrowena', 'sgrm', 'camerafixing', 'robel', 'workrequest', 'mbikinirequest', 'stknw', 'mbtv', 'badgrds', 'instatalkm', 'coversname', 'showcoverpage', 'mcallcheryl', 'laptoprequested', 'pornchanel', 'naivetalk', 'sanal', 'snameworkmelinda', 'mphotos', 'mmirror', 'springstring', 'mphotoediting', 'mpracticegift', 'neibrep', 'bnomn', 'elainefuck', 'sbm', 'mnurseoutfit', 'mnvylingerie', 'hallcamera', 'snamedrink', 'toidoorscrew', 'spiercings', 'beachalone', 'mnameboobs', 'elaineboobs', 'menjoyedtheview', 'mboobstalk', 'mvisitnudebeach', 'b_fightback', 'rowenacall', 'rowena_mom_number', 'report_content', 'mfuckedsober', 'rorepeat', 'browenabm', 'snaked_lunch', 'quick_menu', 'page_name_value', 'device', 'yinitial', 'scroll', 'about', 'thong', 'sgmtb', 'sbesecret', 'bpee_dom', 'sscall', 'sroomride', 'swindowchecked', 'bikini1', 'bikini3', 'bikini2', 'microskirt1', 'stewartcalled', 'sburnt', 'ebizcheck', 'elfllowup', 'melvisit', 'bworked', 'nude_binsta_random1_posted', 'rowena_mom_called', 'hallcamerachecked', 'bphotonaked', 'sgoestost', 'melwork', 'instauploads', 'stewcalled', 'camexpose', 'hallcameracheckedm', 'chbopen', 'btoldcheryl', 'srbm', 'stalkb_rowena', 'skiss_asked', 'smobilegiven', 'bchar', 'schar', 'mchar', 'melchar', 'wrkquestions', 'msex', 'jenteaselingerie', 'sstrip', 'smoneym', 'meldan', 'bworkstarted', 'cellshop', 'mnurse_im', 'windowfound', 'jenopen', 'startnework', 'work_intro', 'bstudied', 'tvwatched', 'snamedrinkminus', 'version', 'name', 'window', 'text_cps', 'save_directory', 'window_icon', 'rowena_mom', 'm_bbruises', 's_bbruises', 'rvisit', 'rowenaslap', 'rdf', 'skiss', 'rowenabffuck', 'sflirtwithotherguys', 'staway', 'bstudy', 'bexercise', 'mrpmt', 'findwindow', 'binstaexp', 'btoiuse', 'beach', 'mwork', 'cherylintro', 'pagecheck', 'rbkisscounter', 'kissrepeat', 'buy_s_phonecounter', 'saction', 'pullsb_repeat', 'rkiss', 'shj', 'sbmrepeat', 'nudebeachtalk', 'sgtruth', 'go_counter', 'sroom13underss', 'msexreturn', 'hidetoiletrowena', 'rowenadp', 'addedchoicerepeat', 'mbphoto', 'dancerepeat', 'spreg', 'mtoiletsuspicious', 'mgready', 'mbvisit', 'giftcardrepeat', 'spregnantno', 'rowenamove', 'gnight', 'melmeeting', 'mwvisit', 'hallcamcheckm', 'sbexerrepeat', 'msuspbs', 'smaid', 'smalonenight', 'mboobskiss', 'ctempted', 'mmorningrepeat', 'bdtchr', 'cherylvisitstrip', 'stalkrp', 'snupset', 'msexwork', 'msfkd', 'mhate', 'wrokmelindrp', 'sfedup', 'robmvisit', 'edpills', 'sdildo', 'aphropack', 'mname', 'bname', 'sname', 'mstripseen']):
            if var in variables:
                report += f"{var}: {variables[var]}\n"
        report += "\n"
        
        # Semua variabel lainnya
        report += "--- OTHER VARIABLES ---\n"
        other_vars = sorted(set(variables.keys()) - set(all_categorized_vars))
        for var in other_vars:
            report += f"{var}: {variables[var]}\n"
        
        # Save to file
        try:
            with open("game_variables_report.txt", "w", encoding="utf-8") as f:
                f.write(report)
            print("Report saved to game_variables_report.txt")
        except:
            print("Could not save report file")
            print(report)
        
        return report
        