# .github/workflows/compile_rpy.yml
name: Compile RPY to RPYC

on:
  workflow_dispatch:  # Hanya manual trigger

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Ren'Py
        run: |
          wget https://www.renpy.org/dl/8.1.3/renpy-8.1.3-sdk.tar.bz2
          tar -xf renpy-8.1.3-sdk.tar.bz2
          echo "$PWD/renpy-8.1.3-sdk" >> $GITHUB_PATH
      - name: Buat folder output (jika belum ada)
        run: mkdir -p to_rpyc_compiled
      - name: Kompilasi .rpy di folder to_rpyc
        run: |
          find to_rpyc -name "*.rpy" -exec sh -c '
            renpy-8.1.3-sdk/renpy.sh "$1" --compile "to_rpyc_compiled/$(basename "$1" .rpy).rpyc"
          ' sh {} \;
      - name: Tampilkan hasil
        run: |
          echo "File hasil kompilasi:"
          ls -l to_rpyc_compiled/