name: Decompile RPYC to RPY
on:
  workflow_dispatch:  # Hanya manual trigger

jobs:
  decompile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"  # Versi paling kompatibel

      - name: Install unrpyc from GitHub
        run: |
          pip install git+https://github.com/CensoredUsername/unrpyc.git
          pip install decompyle3

      - name: Create output directory
        run: mkdir -p to_rpy_decompiled

      - name: Decompile all .rpyc files
        run: |
          find to_rpy -name "*.rpyc" -exec sh -c '
            filepath="$1"
            relpath="${filepath#to_rpy/}"
            outpath="to_rpy_decompiled/${relpath%.rpyc}.rpy"
            mkdir -p "$(dirname "$outpath")"
            unrpyc "$filepath" --output "$outpath"
          ' sh {} \;

      - name: Show results
        run: |
          echo "Decompiled files:"
          find to_rpy_decompiled -type f